name: ungoogled-chromium
version: 91.0.4472.77-1.1-sandbox
base: core20

summary: Google Chromium, sans integration with Google
description: |
  This is Google Chromium, sans dependency on Google web services.

  Ungoogled Chromium retains the default Chromium experience as closely
  as possible. Unlike other Chromium forks that have their own visions
  of a web browser, Ungoogled Chromium is essentially a drop-in replacement
  for Chromium. It also features tweaks to enhance privacy, control,
  and transparency.

confinement: strict
grade: stable

architectures:
  - build-on: amd64

parts:
  chromium:
    plugin: dump
    source: ./sources/tarball
    override-pull: |
      snapcraftctl pull
      chmod 4755 ./chrome-sandbox
    prime:
      - -chrome-sandbox
    stage-packages:
      - libnss3
      - libnspr4

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.joffreybvn.ungoogled-chromium-snapcraft

apps:
  ungoogled-chromium:
    extensions: [gnome-3-38]
    command: chrome-wrapper
    environment:
      DISABLE_WAYLAND: 1
      CHROME_DESKTOP: usr/share/applications/chromium.desktop
      CHROME_CONFIG_HOME: $SNAP_USER_COMMON
    plugs:
      - browser-sandbox
      - audio-playback
      - audio-record
      - bluez # for Web Bluetooth (https://launchpad.net/bugs/1887201)
      - camera
      - cups-control
      - home
      - joystick
      - mount-observe
      - network
      - network-manager
      - password-manager-service
      - pulseaudio # remove once snapd 2.41 is available everywhere
      - raw-usb # for WebUSB (https://launchpad.net/bugs/1780678)
      - removable-media
      - screen-inhibit-control
      - system-packages-doc
      - u2f-devices
      - upower-observe
      # Interfaces:
      - opengl
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
    slots:
      - dbus-daemon
    common-id: com.github.joffreybvn.ungoogled-chromium-snapcraft

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
