name: ungoogled-chromium
version: 89.0.4389.114
base: core20

summary: Google Chromium, sans integration with Google
description: |
  This is Google Chromium, sans dependency on Google web services.

  Ungoogled Chromium retains the default Chromium experience as closely
  as possible. Unlike other Chromium forks that have their own visions
  of a web browser, Ungoogled Chromium is essentially a drop-in replacement
  for Chromium. It also features tweaks to enhance privacy, control,
  and transparency.

confinement: strict
grade: stable

architectures:
  - build-on: amd64

parts:
  base:
    after: [desktop-gnome-platform]
    plugin: dump
    source: ./sources/ungoogled-chromium_89.0.4389.114-1.focal2_amd64.deb
    source-type: deb
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=chromium|Icon=/usr/share/icons/hicolor/256x256/apps/chromium\.png|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/chromium.desktop
    stage-packages:
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatomic1
      - libatspi2.0-0
      - libavcodec58
      - libavformat58
      - libavutil56
      - libcairo2
      - libcups2
      - libdbus-1-3
      - libdrm2
      - libevent-2.1-7
      - libexpat1
      - libflac8
      - libfontconfig1
      - libfreetype6
      - libgbm1
      - libgcc-s1
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libharfbuzz0b
      - libjpeg8
      - libjsoncpp1
      - liblcms2-2
      - libminizip1
      - libnspr4
      - libnss3
      - libopenjp2-7
      - libopus0
      - libpango-1.0-0
      - libpulse0
      - libre2-5
      - libsnappy1v5
      - libstdc++6
      - libvpx6
      - libwebp6
      - libwebpdemux2
      - libwebpmux3
      - libx11-6
      - libxcb1
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxml2
      - libxrandr2
      - libxshmfence1
      - libxslt1.1
      - zlib1g

  common:
    plugin: dump
    source: ./sources/ungoogled-chromium-common_89.0.4389.114-1.focal2_amd64.deb
    source-type: deb

  l10n:
    plugin: dump
    source: ./sources/ungoogled-chromium-l10n_89.0.4389.114-1.focal2_all.deb
    source-type: deb

  driver:
    plugin: dump
    source: ./sources/ungoogled-chromium-driver_89.0.4389.114-1.focal2_amd64.deb
    source-type: deb

  shell:
    plugin: dump
    source: ./sources/ungoogled-chromium-shell_89.0.4389.114-1.focal2_amd64.deb
    source-type: deb

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: gtk
    plugin: make
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

apps:
  ungoogled-chromium:
    command: bin/desktop-launch $SNAP/usr/bin/chromium --no-sandbox
    desktop: usr/share/applications/chromium.desktop
    environment:
      DISABLE_WAYLAND: 1
      CHROME_DESKTOP: usr/share/applications/chromium.desktop
      CHROME_CONFIG_HOME: $SNAP_USER_COMMON
    plugs:
      - browser-support
      - audio-playback
      - audio-record
      - bluez # for Web Bluetooth (https://launchpad.net/bugs/1887201)
      - camera
      - cups-control
      - home
      - joystick
      - mount-observe
      - network
      - network-manager
      - password-manager-service
      - pulseaudio # remove once snapd 2.41 is available everywhere
      - raw-usb # for WebUSB (https://launchpad.net/bugs/1780678)
      - removable-media
      - screen-inhibit-control
      - system-packages-doc
      - u2f-devices
      - upower-observe
      # Interfaces:
      - opengl
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
