name: ungoogled-chromium
version: 87.0.4280.141
base: core20

summary: Google Chromium, sans integration with Google
description: |
  This is Google Chromium, sans dependency on Google web services.

  Ungoogled Chromium retains the default Chromium experience as closely
  as possible. Unlike other Chromium forks that have their own visions
  of a web browser, Ungoogled Chromium is essentially a drop-in replacement
  for Chromium. It also features tweaks to enhance privacy, control,
  and transparency.

confinement: strict
grade: stable

architectures:
  - build-on: amd64

parts:
  base:
    after: [desktop-gtk3]
    plugin: dump
    source: ../deb/ungoogled-chromium_87.0.4280.141-1.unportable1_amd64.deb
    source-type: deb
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=chromium|Icon=/usr/share/icons/hicolor/256x256/apps/chromium\.png|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/chromium.desktop
    stage-packages:
      - lsb-release
      - libatomic1
      - libx11-xcb-dev
      - libxcomposite-dev
      - libxdamage-dev
      - libxi-dev
      - libxrandr-dev
      - libxtst-dev
      - libasound-dev
      - libatk-bridge2.0-0
      - libcairo2
      - libgtk-3-dev
      - libgdk-pixbuf2.0-dev
      - libnspr4-dev
      - libnss3-dev
      - libpci-dev

  common:
    plugin: dump
    source: ../deb/ungoogled-chromium-common_87.0.4280.141-1.unportable1_amd64.deb
    source-type: deb

  l10n:
    plugin: dump
    source: ../deb/ungoogled-chromium-l10n_87.0.4280.141-1.unportable1_all.deb
    source-type: deb

apps:
  ungoogled-chromium:
    command: desktop-launch $SNAP/usr/bin/chromium --no-sandbox --disable-infobars
    desktop: usr/share/applications/chromium.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      DISABLE_WAYLAND: 1
    plugs:
      - browser-support
      - audio-playback
      - audio-record
      - bluez # for Web Bluetooth (https://launchpad.net/bugs/1887201)
      - camera
      - cups-control
      - home
      - joystick
      - mount-observe
      - network
      - network-manager
      - password-manager-service
      - pulseaudio # remove once snapd 2.41 is available everywhere
      - raw-usb # for WebUSB (https://launchpad.net/bugs/1780678)
      - removable-media
      - screen-inhibit-control
      - system-packages-doc
      - u2f-devices
      - unity7 # required for xdg-open to work
      - wayland
      - upower-observe
      - x11
      - opengl
